### ISSUE TITLE
Panel template

### ISSUE THREAD

**Issue by Matteoitaly** [mxmxmx/temps_utile-#23]
Hi,you have please template of panel in pdf? very very thanks

**Comment by mxmxmx** [comment]
hey
you can export fpd to either svg or pdf using front panel designer:
https://www.frontpanelexpress.com/downloads/front_panel_designer/

**Comment by Matteoitaly** [comment]
very thanks!!

2017-04-14 14:00 GMT+02:00 mxmxmx <notifications@github.com>:
