### ISSUE TITLE
Bug that seems to have disappeared... therfore hard to reproduce!

### ISSUE THREAD

**Issue by markfrancombe** [mxmxmx/temps_utile-#29]
Hi, 
Self built module, immediately after first turn on (therefore suspecting build error) seemed to crash (screen went blank operation stopped in the following situation.
1) audio modules connected to both 1 and 2 outs
2) ch 1 clock source changed to INT for testing Module 1 starts... played with mult/div.. all working as it should
3) went into ch 2 and set clock source to INT, no operation occured... pressed up button, unit crashed.

This situation was completely reproducible every time, every power cycle, UNTIL...
I read the manual and learned about the up button/long press, to get to BPM counter (was wondering about that actually, when I was testing the ch1. ("wheres the f...ing BPM?" I muttered)

However performing this combo, seems to have fixed the issue, tried power cycling even with no setting save and it now does NOT crash and seems to work 100%

Lovely module... fun so far!

**Comment by mxmxmx** [comment]
ok, closing this ... (hopefully it didn't reappear!)
