### ISSUE TITLE
New Arduino IDE (> 1.6.9) breaks TU compile

### ISSUE THREAD

**Issue by jeremybernstein** [mxmxmx/temps_utile-#3]
Arduino made a change to the IDE which restricts automatic compilation of resources in subfolders (https://github.com/arduino/arduino-builder/pull/148) which breaks this project (linkage errors). You may need to explicitly #include the cpp files (ugly) or simply move the files to the top-level or a src/ folder.

**Comment by mxmxmx** [comment]
brilliant (and thanks for the heads-up).

does this work?
https://github.com/mxmxmx/temps_utile-/tree/fix_6_11

**Comment by jeremybernstein** [comment]
Yes it does.

**Comment by mxmxmx** [comment]
ok, cool. it doesn't seem to break backwards compatibility either.
