### ISSUE TITLE
Clock source setting do not save

### ISSUE THREAD

**Issue by GitBruno** [mxmxmx/temps_utile-#30]
I expected `Clock source` setting to be included in save. (Running 1.2.2 beta)

Is everything saved or are some elements excluded?

Notes:
    I don't see the "saving ....." message, just the growing square
    However clock multiplications did  seem to save correctly
    Switching global trigger on/off does not seem to matter

**Comment by Banshee700** [comment]
Yep, i mentioned that as well to Max
