### ISSUE TITLE
clock doesn't start

### ISSUE THREAD

**Issue by evancorylevine** [mxmxmx/temps_utile-#31]
I have an issue wherein the clock doesn't start on channel one unless I change the clock source and then change it back again. I am in MULT mode with the PW at 50% and div at /48. I saved this state, but whenever I restart the power the clock source has to be changed and then changed back to TR1 for the clock to begin on this channel. My second channel just starts when I power up. It doesn't need attention.

**Comment by GitBruno** [comment]
There must be something wrong with your hardware build. Did you solve this?

**Comment by mxmxmx** [comment]
temporary fix here now https://github.com/mxmxmx/temps_utile-/tree/1.3b
