### ISSUE TITLE
Gate output ?

### ISSUE THREAD

**Issue by RomeoFF** [mxmxmx/temps_utile-#37]
I haven’t tried the module yet but is it possible to make it work with gate output instead of trigger only ? (For example, instead of random pulse rhythms, we could get random rhythms with random sustain duration by pluging into an ADSR module)

**Comment by mxmxmx** [comment]
there's a pulsewidth parameter, which you can CV and/or set manually. it maxes out at 50% duty cycle, IIRC, so should be possible.
