### ISSUE TITLE
Enhancement Request: Waveforms/LFOs?

### ISSUE THREAD

**Issue by jkmaxwell** [mxmxmx/temps_utile-#38]
Hi. Not sure if it's possible, but it would be incredible to see the temps incorporate some of the Pamela's New Workout features like clocked waveforms.

**Comment by mxmxmx** [comment]
possible: mostly no. the outputs, except #4, are GPIO, so they can only be on/off. output #4 is a 12 bit DAC though, so moving some of the clocked LFO stuff from OC would be doable.
