### ISSUE TITLE
external clock different threshold?

### ISSUE THREAD

**Issue by thomasvanta** [mxmxmx/temps_utile-#40]
Hi,
I'd like to use my temps with the LZX video system (0-1V range).
This voltage won't trigger the clock input. There's adapters like the lzx bridge or the cadet, but I was wondering if a 'clock-in threshold' would be an easy parameter to implement in the general settings or if its tight to hardware.
:)

**Comment by mxmxmx** [comment]
hi,

the threshold (~ 2.8V) is a hardware thing, try removing the two 33k resistors at the TR inputs (ie the voltage dividers before the NPNs)
