### ISSUE TITLE
Adding Swing?

### ISSUE THREAD

**Issue by okyeron** [mxmxmx/temps_utile-#5]
I had the idea that being able to "swing" the beat for any Temps output would be a really neat feature. The idea being to delay all the even-numbered 16th notes within the beat (2, 4, 6, 8, etc.) 

A friend helped me hack together some basic code for this, but we're not sure exactly how to implement it in the codebase so I thought I'd post it here to see if this is something useful.

I tried this around line 838 in the APP_CLK.ino file:
(below the brute force ugly sync hack)

`     // ATTEMPT AT SWING

```
// enc_value = .5;  
// this would be a setting for swing amount from encoder input or settings
// some value between 0-1 where 50% is no swing, 66% being triplets

 uint32_t swing_val = 2*channel_frequency_in_ticks_ * enc_value;
 uint32_t frame_length_in_ticks = (clk_cnt_%2 == 0) ? (swing_val) : (2*channel_frequency_in_ticks_- swing_val);

 // time to output ? 
 if (subticks_ >= frame_length_in_ticks && _sync) { // ckm: changed 'channel_frequency_in_ticks_' to 'frame_length_in_ticks'
```

`

We made a couple assumptions that clk_cnt_ was "one beat" and that shifting the value for channel_frequency_in_ticks_ would swing the beat output.

**Comment by mxmxmx** [comment]
see here now (which adds phase offset, not swing)

https://github.com/mxmxmx/temps_utile-/tree/sync_variation
